sudo: false
language: python
dist: focal
env:
  - NODE_VERSION="16"
before_install:
  - nvm install $NODE_VERSION
python:
  - "3.10"
install:
  - pip install -r requirements.txt
  - pip install tox-travis
before_script:
  - tox
script:
  - cd npm
  - npm ci
  - npm run copy:schemas
  - npm run semantic-release
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh ../scripts/automated-update-blockcerts.org.sh; fi' # if no changes (aka npm release), no commit then no PR
  - cd ..
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh semantic-release.sh; fi'
