sudo: false
language: python
dist: focal
branches:
  only:
    - master
env:
  - NODE_VERSION="16"
before_install:
  - nvm install $NODE_VERSION
python:
  - "3.10"
install: pip install tox-travis
script: tox
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then . ./semantic-release.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then . ./release_npm_package.sh; fi'
